name: CI React Tailwind UNAH

on:
  push:
    branches: [main, tailwind-migration]
  pull_request:
    branches: [main]

jobs:
  validate-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Run linter (ESLint + Prettier)
        run: npm run lint

      - name: Run tests (Jest / RTL si existen)
        run: npm test

      - name: Build React app
        run: npm run build
